### ISSUE TITLE
cask install/upgrade leaves `com.apple.quarantine` on GraalVM, blocking execution

### ISSUE THREAD

**Issue by slippycheeze** [graalvm/homebrew-tap#16]
After installation or upgrade of the GraalVM 11 cask (multiple versions, 19 and 20) the `/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0` directory and content have the `com.apple.quarantine` xattr present.

This is the "normal" behaviour of downloaded software on MacOS, but it causes problems running from the CLI: it pops up a dialog box informing me that the software can't be run, and allows no override.

To resolve this it is sufficient to execute this command:
```shell
xattr -d -r com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0
```

I'd suggest updating the cask to automatically apply that to the appropriate directory after unpacking and moving.  That'd strip off the quarantine flag, allowing execution of the content.

Normally I wouldn't encourage automatically removing an OS security flag, but in this case it seems justified: I explicitly requested the software be installed via brew cask, so I'd expect it to be flagged as "safe" to use immediately afterwards.

**Comment by dwijnand** [comment]
The `-r` isn't necessary.

**Comment by dougxc** [comment]
@fniephaus would you mind taking care of this?

**Comment by fniephaus** [comment]
AFAICT one need to invoke some binary (e.g. java) of the bundle first, only then will macOS add the quarantine attribute. I will have to figure out if that it true and how this could be part of the cask. Signing the bundle would be the right fix to be honest.

**Comment by dwijnand** [comment]
Adding the info to the caveat section would already be a helping hand.

**Comment by fniephaus** [comment]
> Adding the info to the caveat section would already be a helping hand.

That's a good idea, much better than automatically circumventing security measures.

**Comment by fniephaus** [comment]
Please have a look at #17.
