### ISSUE TITLE
“graalvm-ce-java11-20.3.0” is damaged and can’t be opened

### ISSUE THREAD

**Issue by mafulafunk** [graalvm/homebrew-tap#28]
running 

java -v

on macOS Catalina: 10.15.7 (19H114)

leeds to:“graalvm-ce-java11-20.3.0” is damaged and can’t be opened.

› brew info graalvm-ce-java11
graalvm-ce-java11: 20.3.0
https://www.graalvm.org/
/usr/local/Caskroom/graalvm-ce-java11/20.3.0 (154B)
From: https://github.com/graalvm/homebrew-tap/blob/HEAD/Casks/graalvm-ce-java11.rb
==> Name
[...]

**Comment by mafulafunk** [comment]
My bad so sorry.
I had a typo in:
xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.3.0

**Comment by juanmbellini** [comment]
How did you solve this? I have the same issue

**Comment by ezzarghili** [comment]
> How did you solve this? I have the same issue

https://github.com/graalvm/homebrew-tap#macos-catalina-specifics

**Comment by max-empirys** [comment]
As mentioned here https://www.graalvm.org/22.2/docs/getting-started/macos/ we should do this before moving to `/Library/Java/JavaVirtualMachines`: 
![image](https://user-images.githubusercontent.com/83598909/182804860-d7471e53-b86a-4de5-a1ab-19903058e73a.png)

`sudo xattr -r -d com.apple.quarantine /path/to/graalvm`

**Comment by daggerok** [comment]
Documentation needs to be fixed, as far there are path to archive file, not path to graalvm folder
<img width="1307" alt="image" src="https://github.com/graalvm/homebrew-tap/assets/2445604/4e01f9a9-682f-40cd-9e96-dcc672fe2594">

**Comment by fniephaus** [comment]
@daggerok thanks for the suggestion. Actually both approaches work: removing the quarantine attribute from the archive before extracting and removing the attribute from the extracted GraalVM folder and all its subdirectories and files. Removing it from the archive is a bit easier, so that's what we are recommending in our docs. Since homebrew takes care of the extracting step, the casks in this tap can only recommend the 2nd approach. Hope this makes sense!

**Comment by daggerok** [comment]
@fniephaus its true if you installing it from archive, but in case if you using brew installation, in the end as a result you'll have  folder ls /Library/Java/JavaVirtualMachines/graalvm-$version.jdk

**Comment by fniephaus** [comment]
The caveat printed when installing one of the GraalVM casks actually prints the correct command for the corresponding installation: https://github.com/graalvm/homebrew-tap/blob/5b0ebcb8d238110ad772142b4e145fd441bc888c/Casks/graalvm-jdk22.rb#L36

Maybe you have missed this?

**Comment by daggerok** [comment]
@fniephaus maybe... if it will be printed than nothing else is needed
