### ISSUE TITLE
Files installed with `graalvm-ce-lts-java11` are broken

### ISSUE THREAD

**Issue by seijikohara** [graalvm/homebrew-tap#31]
I ran `brew install --cask graalvm/tap/graalvm-ce-lts-java11` and it installed on `/Library/Java/JavaVirtualMachines/graalvm-ce-lts-java11-20.3.1`.

Then when I run `/Library/Java/JavaVirtualMachines/graalvm-ce-lts-java11-20.3.1/Contents/Home/bin/java -version`, I get a dialog saying the file is broken.

![image](https://user-images.githubusercontent.com/9543980/107911424-ec4ec300-6f9f-11eb-9e4a-bc7f16e42d6e.png)

- Environment

```
$ neofetch
                    'c.          seijikohara@MacBook-Pro-Seiji.local
                 ,xNMM.          -----------------------------------
               .OMMMMo           OS: macOS 11.2.1 20D74 x86_64
               OMMM0,            Host: MacBookPro15,2
     .;loddo:' loolloddol;.      Kernel: 20.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 3 days, 20 hours, 22 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 135 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050@2x, 2560x1440@2x, 1024x768@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Graphite (Light)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: SFMono-Regular 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i5-8259U (8) @ 2.30GHz
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel Iris Plus Graphics 655
       .cooc,.    .,coo:.        Memory: 11474MiB / 16384MiB
```

**Comment by dougxc** [comment]
Any ideas about this @fniephaus ?

**Comment by fniephaus** [comment]
Yes, it looks like he didn't remove the quarantine flag (as mentioned in the installation notice).

Here's what you have to do: https://github.com/oracle/graal/issues/1724#issuecomment-540160024

**Comment by seijikohara** [comment]
It was resolved by running `xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-lts-java11-20.3.1`.
Thank you for your advice.

**Comment by anentropic** [comment]
Maybe the info in the readme needs updating

Currently is says something specific to Catalina, with a different error message

I just hit this in Ventura (macos 13) and get this error message:
<img width="262" alt="Screenshot 2022-12-16 at 23 12 22" src="https://user-images.githubusercontent.com/147840/208203660-c744660b-6fbb-4835-b83a-feadfd82669b.png">

it is fixed by the `xattr`  tip still though
