### ISSUE TITLE
Update to release 22.0.0.2

### ISSUE THREAD

**Issue by dr-eme** [graalvm/homebrew-tap#42]
GraalVM version 22.0.0.2 has been released.
https://github.com/graalvm/graalvm-ce-builds/releases

Cask graalvm-ce-java11.rb shall be updated with
  version "22.0.0.2"
  sha256 "8280159b8a66c51a839c8079d885928a7f759d5da0632f3af7300df2b63a6323"

while cask graalvm-ce-java17.rb shall be updated with
  version "22.0.0.2"
  sha256 "d54af9d1f4d0d351827395a714ed84d2489b023b74a9c13a431cc9d31d1e8f9a"

Thanks

**Comment by fniephaus** [comment]
Thanks for the issue. We've updated the casks for the 22.0.0.2 release. Sorry for the delay!
