### ISSUE TITLE
Apple M1: bad CPU type in executable

### ISSUE THREAD

**Issue by avelino** [graalvm/homebrew-tap#43]
CPU: Apple M1
OS: macOS Monterey

```
...
==> Installing Cask graalvm-ce-java11
==> Moving Generic Artifact 'graalvm-ce-java11-22.0.0.2' to '/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.0.0.2'
🍺  graalvm-ce-java11 was successfully installed!
❯ ~ /opt/homebrew/Caskroom/graalvm-ce-java11/22.0.0.2/graalvm-ce-java11-22.0.0.2/Contents/Home/bin/java
zsh: bad CPU type in executable: /opt/homebrew/Caskroom/graalvm-ce-java11/22.0.0.2/graalvm-ce-java11-22.0.0.2/Contents/Home/bin/java
```

**Comment by fniephaus** [comment]
GraalVM currently does not support Apple M1 chips yet (we are actively working on it, see: https://github.com/oracle/graal/issues/2666). In the meantime, you can run GraalVM on Rosetta 2. For that, you need to run `brew` in a [Rosetta-enabled terminal](https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/).

**Comment by fniephaus** [comment]
Hey @avelino, yes, M1 support has landed in GraalVM.  However, we have to wait for the 22.1 release, which is due next month, before we can add support for M1 machines to this tap. In the meantime, you can try out dev builds: https://github.com/graalvm/graalvm-ce-dev-builds/releases/latest

**Comment by KevinRoebert** [comment]
Is it possible to create a homebrew tap for the nightly build?

**Comment by KevinRoebert** [comment]
> Do you have a good use case for dev builds beyond M1 support?

Currently, no ^^

**Comment by fniephaus** [comment]
> Currently, no ^^

Fair enough! Anyway, I managed to look into this so now, you can run the following to install an M1 dev build:

```bash
brew install --cask graalvm/tap/graalvm-ce-java17
# or
brew install --cask graalvm/tap/graalvm-ce-java11
```

**Comment by brandonstubbs** [comment]
```bash
# uname -m
arm64

# brew install --cask graalvm/tap/graalvm-ce-java17
```

![image](https://user-images.githubusercontent.com/3731434/160010684-7a96ff37-9a51-4621-a5b5-791d69115f4c.png)

**Comment by KevinRoebert** [comment]
Have you removed the quarantine bit? See also https://github.com/oracle/graal/issues/2666#issuecomment-1074884020

```
$ sudo xattr -r -d com.apple.quarantine /path/to/GRAALVM_HOME
```

**Comment by brandonstubbs** [comment]
@KevinRoebert thanks that worked!

**Comment by fniephaus** [comment]
Closed by https://github.com/graalvm/homebrew-tap/commit/0560e9629b2326e23b6b5dbd8b1cdf132de3fffe.

With the new `22.1.0` release, GraalVM has shipped experimental support Apple Silicon.
