### ISSUE TITLE
Update to 23.0.1

### ISSUE THREAD

**Issue by andrewstein** [graalvm/homebrew-tap#49]
GraalVM 23.0.1 has been released: https://github.com/graalvm/graalvm-ce-builds/releases/tag/graal-23.0.1
Please update.

**Comment by fniephaus** [comment]
There is no such thing as GraalVM 23.0.1. The latest releases are called GraalVM for JDK 17 and JDK 20, and they are already supported by this tap, see README:
```
# Current Oracle GraalVM releases
brew install --cask graalvm/tap/graalvm-jdk17
brew install --cask graalvm/tap/graalvm-jdk20

# Current GraalVM CE releases
brew install --cask graalvm/tap/graalvm-community-jdk17
brew install --cask graalvm/tap/graalvm-community-jdk20
```

Hope this helps!
