### ISSUE TITLE
Install graalvm with brew

### ISSUE THREAD

**Issue by liaozan** [graalvm/homebrew-tap#50]
Can you modify the install script to install the same version of graalvm in the same directory? 
Now that graalvm is installed via brew with major and minor version numbers, you need to reset the JAVA_HOME each time you update graalvm.

**Comment by liaozan** [comment]
<img width="168" alt="image" src="https://github.com/graalvm/homebrew-tap/assets/26990889/0b0faf39-1642-4c96-83a9-04891f9ae35b">

**Comment by fniephaus** [comment]
Do you mean you'd like one directory per Java version? For example:
- `graalvm-jdk-17`
- `graalvm-jdk-21`
- ...

or are you looking for one directory for latest GraalVM? For example:
- `graalvm-jdk-latest`

Maybe you want to consider using [SDKMAN!](https://sdkman.io/), which makes it easy to upgrade and switch between different `JAVA_HOME`s.

**Comment by liaozan** [comment]
> 
> * `graalvm-jdk-17`
> * `graalvm-jdk-21`
> * ...

Yes, i want this
