### ISSUE TITLE
 “graalvm-ce-19.2.0.1” can’t be opened because its integrity cannot be verified.

### ISSUE THREAD

**Issue by ampersanda** [graalvm/homebrew-tap#6]
It seems that on MacOS Catalina, latest version of it can't be executed properly.

![Screen Shot 2019-10-03 at 12 43 16](https://user-images.githubusercontent.com/13579812/66102130-6f55c000-e5db-11e9-9688-f25591c00ec8.png)

I tried fresh install and set `$GRAALVM_HOME` to install `native-image` and this happens

![Screen Shot 2019-10-03 at 12 38 15](https://user-images.githubusercontent.com/13579812/66101984-f0608780-e5da-11e9-8d51-39c2210df400.png)
![Screen Shot 2019-10-03 at 12 38 17](https://user-images.githubusercontent.com/13579812/66101985-f0f91e00-e5da-11e9-93ea-1cd19cacf6b5.png)

Thanks

**Comment by ampersanda** [comment]
temporarily I disable to achieve this fix, by using command

`sudo spctl --master-disable`

**Comment by fniephaus** [comment]
`xattr -d com.apple.quarantine $GRAALVM_HOME` should be enough, no need to disable Gatekeeper entirely.

**Comment by richmidwinter** [comment]
That env variable wasn't set for me, and it wasn't the `Contents/Home` dir, but this worked:

`xattr -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-19.3.0`

**Comment by iamyaoxi** [comment]
Apparently, it's not working for me.... Any other solution perhaps? 

Result:
`xattr: /Users/yosi/GraalVM: No such xattr: com.apple.quarantine`

**Comment by fniephaus** [comment]
@iamyaoxi what happens when you try to open your GraalVM's `bin/java`? Do you see a warning? What happens if you run the command afterwards?

**Comment by dmgorsky** [comment]
> Apparently, it's not working for me.... Any other solution perhaps?
> 
> I tried:
> `xattr -d com.apple.quarantine /Library/GraalVM`
> 
> Which is the location of the GraalVM.
> 
> Result:
> `xattr: /Users/yosi/GraalVM: No such xattr: com.apple.quarantine`

```xattr -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce*```
